from __future__ import annotations

from datetime import datetime
from typing import ClassVar, Optional

__version__: str
MODEL_VERSION: str
SIDERUST_VERSION: str
SIDERUST_SOURCE: str

class NsbError(Exception): ...
class DataParseError(NsbError): ...
class DataMissingError(NsbError): ...
class InvalidMapError(NsbError): ...
class OutOfRangeError(NsbError): ...
class UnsupportedError(NsbError): ...
class InterpolationError(NsbError): ...
class IoError(NsbError): ...

class Observer:
    def __init__(self, *, latitude_deg: float, longitude_deg: float, elevation_m: float) -> None: ...
    @property
    def latitude_deg(self) -> float: ...
    @property
    def longitude_deg(self) -> float: ...
    @property
    def elevation_m(self) -> float: ...

class Target:
    def __init__(self, *, ra_deg: float, dec_deg: float) -> None: ...
    @property
    def ra_deg(self) -> float: ...
    @property
    def dec_deg(self) -> float: ...
    @property
    def reference_frame(self) -> str: ...

class SiteProfile:
    GENERIC_CLEAR_SKY: ClassVar[SiteProfile]
    CTA_NORTH: ClassVar[SiteProfile]
    CTA_SOUTH: ClassVar[SiteProfile]
    def as_str(self) -> str: ...

class MoonlightModel:
    KRISCIUNAS_SCHAEFER1991: ClassVar[MoonlightModel]
    JONES2013_SPECTRAL: ClassVar[MoonlightModel]
    def as_str(self) -> str: ...

class AirglowModel:
    PARANAL_NOLL_SKY_CALC_FORS1: ClassVar[AirglowModel]
    def as_str(self) -> str: ...

class ZodiacalModel:
    LEINERT1998: ClassVar[ZodiacalModel]
    def as_str(self) -> str: ...

class ZodiacalExtinction:
    NONE: ClassVar[ZodiacalExtinction]
    NOLL2012_APPROX: ClassVar[ZodiacalExtinction]
    def as_str(self) -> str: ...

class StarlightProduct:
    BUNDLED_PRODUCTION_GAIA_DR3: ClassVar[StarlightProduct]
    def as_str(self) -> str: ...
    @staticmethod
    def bundled_production_available() -> bool: ...

class ComponentMask:
    ZODIACAL: ClassVar[ComponentMask]
    STARLIGHT: ClassVar[ComponentMask]
    AIRGLOW: ClassVar[ComponentMask]
    MOON: ClassVar[ComponentMask]
    DEFAULT: ClassVar[ComponentMask]
    ALL: ClassVar[ComponentMask]
    def __init__(self, bits: int) -> None: ...
    @property
    def bits(self) -> int: ...
    def contains(self, other: ComponentMask) -> bool: ...
    def __or__(self, other: ComponentMask) -> ComponentMask: ...
    def __and__(self, other: ComponentMask) -> ComponentMask: ...

class NsbModelConfig:
    def __init__(self) -> None: ...
    @staticmethod
    def generic_clear_sky() -> NsbModelConfig: ...
    @staticmethod
    def cta_n_planning() -> NsbModelConfig: ...
    @staticmethod
    def cta_s_planning() -> NsbModelConfig: ...
    def with_site_profile(self, profile: SiteProfile) -> NsbModelConfig: ...
    def with_moonlight_model(self, model: MoonlightModel) -> NsbModelConfig: ...
    def with_airglow_model(self, model: AirglowModel) -> NsbModelConfig: ...
    def with_automatic_airglow(self) -> NsbModelConfig: ...
    def with_zodiacal_model(self, model: ZodiacalModel) -> NsbModelConfig: ...
    def with_zodiacal_extinction(self, extinction: ZodiacalExtinction) -> NsbModelConfig: ...
    def with_starlight_product(self, product: StarlightProduct) -> NsbModelConfig: ...
    @property
    def site_profile(self) -> SiteProfile: ...
    @property
    def moonlight_model(self) -> MoonlightModel: ...
    @property
    def zodiacal_model(self) -> ZodiacalModel: ...
    @property
    def zodiacal_extinction(self) -> ZodiacalExtinction: ...
    @property
    def airglow_selection(self) -> str: ...
    @property
    def airglow_model(self) -> Optional[AirglowModel]: ...
    @property
    def starlight_product(self) -> Optional[str]: ...
    @property
    def is_airglow_site_calibrated(self) -> bool: ...

class PointQuery:
    def __init__(self, observer: Observer, time: datetime, target: Target, *, components: Optional[ComponentMask] = ...) -> None: ...
    def with_components(self, components: ComponentMask) -> PointQuery: ...
    @property
    def observer(self) -> Observer: ...
    @property
    def time(self) -> datetime: ...
    @property
    def target(self) -> Target: ...
    @property
    def components(self) -> ComponentMask: ...

class ThresholdQuery:
    def __init__(self, observer: Observer, target: Target, start: datetime, end: datetime, threshold_photons_cm2_ns_sr: float, *, components: Optional[ComponentMask] = ..., sample_step_s: float = ...) -> None: ...
    def with_components(self, components: ComponentMask) -> ThresholdQuery: ...
    def with_sample_step_s(self, sample_step_s: float) -> ThresholdQuery: ...
    def with_sun_altitude_ceiling_deg(self, value: Optional[float]) -> ThresholdQuery: ...
    def with_target_altitude_floor_deg(self, value: Optional[float]) -> ThresholdQuery: ...
    @property
    def observer(self) -> Observer: ...
    @property
    def target(self) -> Target: ...
    @property
    def start(self) -> datetime: ...
    @property
    def end(self) -> datetime: ...
    @property
    def threshold_photons_cm2_ns_sr(self) -> float: ...
    @property
    def sample_step_s(self) -> float: ...
    @property
    def sun_altitude_ceiling_deg(self) -> Optional[float]: ...
    @property
    def target_altitude_floor_deg(self) -> Optional[float]: ...
    @property
    def components(self) -> ComponentMask: ...

class BandDiagnostic:
    @property
    def convention(self) -> str: ...
    @property
    def b_reference_nm(self) -> float: ...
    @property
    def v_reference_nm(self) -> float: ...
    @property
    def zero_point_mag_per_arcsec2(self) -> float: ...

class NsbComponentMetadata:
    @property
    def status(self) -> str: ...
    @property
    def provenance(self) -> str: ...
    @property
    def validated_domain(self) -> str: ...
    @property
    def band_diagnostic(self) -> BandDiagnostic: ...
    @property
    def airglow_selection_kind(self) -> Optional[str]: ...
    @property
    def airglow_requested_model(self) -> Optional[str]: ...
    @property
    def airglow_resolved_model(self) -> Optional[str]: ...
    @property
    def airglow_used_automatic_fallback(self) -> Optional[bool]: ...
    @property
    def airglow_fallback_reason(self) -> Optional[str]: ...
    @property
    def airglow_physical_outcome(self) -> Optional[str]: ...
    @property
    def airglow_physical_zero_reason(self) -> Optional[str]: ...
    @property
    def solar_activity_provenance(self) -> Optional[str]: ...

class NsbComponent:
    @property
    def name(self) -> str: ...
    @property
    def integrated_photons_cm2_ns_sr(self) -> float: ...
    @property
    def b_flux_s10(self) -> float: ...
    @property
    def v_flux_s10(self) -> float: ...
    @property
    def relative_uncertainty(self) -> Optional[float]: ...
    @property
    def statistical_uncertainty_photons_cm2_ns_sr(self) -> Optional[float]: ...
    @property
    def systematic_uncertainty_photons_cm2_ns_sr(self) -> Optional[float]: ...
    @property
    def total_uncertainty_photons_cm2_ns_sr(self) -> Optional[float]: ...
    @property
    def metadata(self) -> NsbComponentMetadata: ...

class NsbComponentDescriptor:
    @property
    def name(self) -> str: ...
    @property
    def metadata(self) -> NsbComponentMetadata: ...

class NsbResult:
    @property
    def integrated_photons_cm2_ns_sr(self) -> float: ...
    @property
    def b_mag_per_arcsec2(self) -> float: ...
    @property
    def v_mag_per_arcsec2(self) -> float: ...
    @property
    def components(self) -> list[NsbComponent]: ...
    @property
    def band_diagnostic(self) -> BandDiagnostic: ...

class UtcPeriod:
    @property
    def start(self) -> datetime: ...
    @property
    def end(self) -> datetime: ...

class ThresholdQueryResult:
    @property
    def threshold_photons_cm2_ns_sr(self) -> float: ...
    @property
    def periods(self) -> list[UtcPeriod]: ...

class SiteWindowContext: ...

class NsbEvaluator:
    def __init__(self, config: Optional[NsbModelConfig] = ...) -> None: ...
    @property
    def config(self) -> NsbModelConfig: ...
    def describe_components(self, observer: Observer, components: ComponentMask) -> list[NsbComponentDescriptor]: ...
    def evaluate(self, query: PointQuery) -> NsbResult: ...
    def prepare_site_window_context(self, query: ThresholdQuery) -> SiteWindowContext: ...
    def periods_below_threshold(self, query: ThresholdQuery) -> ThresholdQueryResult: ...
    def periods_below_threshold_with_context(self, context: SiteWindowContext, query: ThresholdQuery) -> ThresholdQueryResult: ...
