"""Python facade for the Rust NSB evaluator and planning API."""

# Observer and Direction are compatibility exports today. Once the Siderust
# Python package is version-compatible with NSB, these two imports can move to
# `siderust` without changing the private Rust extension layout.
from ._nsb import (
    MODEL_VERSION,
    SIDERUST_SOURCE,
    SIDERUST_VERSION,
    AirglowModel,
    ComponentMask,
    DataMissingError,
    DataParseError,
    Direction,
    InterpolationError,
    InvalidMapError,
    IoError,
    MoonlightModel,
    NsbComponent,
    NsbComponentMetadata,
    NsbError,
    NsbEvaluator,
    NsbModelConfig,
    NsbResult,
    Observer,
    OutOfRangeError,
    PointQuery,
    SiteProfile,
    SiteWindowContext,
    ThresholdQuery,
    ThresholdQueryResult,
    UnsupportedError,
    ZodiacalExtinction,
    __version__,
)

__all__ = [
    "MODEL_VERSION",
    "SIDERUST_SOURCE",
    "SIDERUST_VERSION",
    "AirglowModel",
    "ComponentMask",
    "DataMissingError",
    "DataParseError",
    "Direction",
    "InterpolationError",
    "InvalidMapError",
    "IoError",
    "MoonlightModel",
    "NsbComponent",
    "NsbComponentMetadata",
    "NsbError",
    "NsbEvaluator",
    "NsbModelConfig",
    "NsbResult",
    "Observer",
    "OutOfRangeError",
    "PointQuery",
    "SiteProfile",
    "SiteWindowContext",
    "ThresholdQuery",
    "ThresholdQueryResult",
    "UnsupportedError",
    "ZodiacalExtinction",
    "__version__",
]
