from datetime import datetime
from typing import Final

__version__: str
MODEL_VERSION: str
SIDERUST_VERSION: str
SIDERUST_SOURCE: str

class NsbError(Exception): ...
class DataParseError(NsbError): ...
class DataMissingError(NsbError): ...
class InvalidMapError(NsbError): ...
class OutOfRangeError(NsbError): ...
class UnsupportedError(NsbError): ...
class InterpolationError(NsbError): ...
class IoError(NsbError): ...

class Observer:
    def __init__(self, lon_deg: float, lat_deg: float, height_m: float = 0.0) -> None: ...
    @property
    def lon_deg(self) -> float: ...
    @property
    def lat_deg(self) -> float: ...
    @property
    def height_m(self) -> float: ...

class Direction:
    def __init__(self, ra_deg: float, dec_deg: float) -> None: ...
    @property
    def ra_deg(self) -> float: ...
    @property
    def dec_deg(self) -> float: ...

class SiteProfile:
    GENERIC_CLEAR_SKY: Final[SiteProfile]
    CTA_NORTH: Final[SiteProfile]
    CTA_SOUTH: Final[SiteProfile]
    def as_str(self) -> str: ...

class MoonlightModel:
    KRISCIUNAS_SCHAEFER1991: Final[MoonlightModel]
    JONES2013_SPECTRAL: Final[MoonlightModel]
    def as_str(self) -> str: ...

class AirglowModel:
    PARANAL_NOLL_SKY_CALC_FORS1: Final[AirglowModel]
    def as_str(self) -> str: ...

class ZodiacalExtinction:
    NONE: Final[ZodiacalExtinction]
    NOLL2012_APPROX: Final[ZodiacalExtinction]
    def as_str(self) -> str: ...

class ComponentMask:
    ZODIACAL: Final[ComponentMask]
    STARLIGHT: Final[ComponentMask]
    AIRGLOW: Final[ComponentMask]
    MOON: Final[ComponentMask]
    DEFAULT: Final[ComponentMask]
    ALL: Final[ComponentMask]
    @property
    def bits(self) -> int: ...
    def contains(self, other: ComponentMask) -> bool: ...
    def __or__(self, other: ComponentMask) -> ComponentMask: ...
    def __and__(self, other: ComponentMask) -> ComponentMask: ...

class NsbModelConfig:
    @staticmethod
    def generic_clear_sky() -> NsbModelConfig: ...
    def with_site_profile(self, profile: SiteProfile) -> NsbModelConfig: ...
    def with_moonlight_model(self, model: MoonlightModel) -> NsbModelConfig: ...
    def with_airglow_model(self, model: AirglowModel) -> NsbModelConfig: ...
    def with_automatic_airglow(self) -> NsbModelConfig: ...
    def with_zodiacal_extinction(self, extinction: ZodiacalExtinction) -> NsbModelConfig: ...
    @property
    def site_profile(self) -> SiteProfile: ...
    @property
    def moonlight_model(self) -> MoonlightModel: ...
    @property
    def airglow_selection(self) -> str: ...
    @property
    def airglow_model(self) -> AirglowModel | None: ...
    @property
    def zodiacal_extinction(self) -> ZodiacalExtinction: ...
    @property
    def is_airglow_site_calibrated(self) -> bool: ...

class PointQuery:
    def __init__(self, observer: Observer, time: datetime, target: Direction, *, components: ComponentMask | None = None) -> None: ...
    @property
    def observer(self) -> Observer: ...
    @property
    def time(self) -> datetime: ...
    @property
    def target(self) -> Direction: ...
    @property
    def components(self) -> ComponentMask: ...

class ThresholdQuery:
    def __init__(self, observer: Observer, target: Direction, start: datetime, end: datetime, threshold_photons_cm2_ns_sr: float, *, components: ComponentMask | None = None, sample_step_s: float = 600.0, sun_altitude_ceiling_deg: float | None = -18.0, target_altitude_floor_deg: float | None = 0.0) -> None: ...
    @property
    def observer(self) -> Observer: ...
    @property
    def target(self) -> Direction: ...
    @property
    def start(self) -> datetime: ...
    @property
    def end(self) -> datetime: ...
    @property
    def threshold_photons_cm2_ns_sr(self) -> float: ...
    @property
    def components(self) -> ComponentMask: ...
    @property
    def sample_step_s(self) -> float: ...
    @property
    def sun_altitude_ceiling_deg(self) -> float | None: ...
    @property
    def target_altitude_floor_deg(self) -> float | None: ...

class NsbComponentMetadata:
    @property
    def status(self) -> str: ...
    @property
    def provenance(self) -> str: ...
    @property
    def validated_domain(self) -> str: ...
    @property
    def airglow_selection_kind(self) -> str | None: ...
    @property
    def airglow_requested_model(self) -> str | None: ...
    @property
    def airglow_resolved_model(self) -> str | None: ...
    @property
    def airglow_used_automatic_fallback(self) -> bool | None: ...
    @property
    def airglow_fallback_reason(self) -> str | None: ...
    @property
    def airglow_physical_outcome(self) -> str | None: ...
    @property
    def airglow_physical_zero_reason(self) -> str | None: ...
    @property
    def solar_activity_provenance(self) -> str | None: ...

class NsbComponent:
    @property
    def name(self) -> str: ...
    @property
    def integrated_photons_cm2_ns_sr(self) -> float: ...
    @property
    def b_flux_s10(self) -> float: ...
    @property
    def v_flux_s10(self) -> float: ...
    @property
    def relative_uncertainty(self) -> float | None: ...
    @property
    def statistical_uncertainty_photons_cm2_ns_sr(self) -> float | None: ...
    @property
    def systematic_uncertainty_photons_cm2_ns_sr(self) -> float | None: ...
    @property
    def total_uncertainty_photons_cm2_ns_sr(self) -> float | None: ...
    @property
    def metadata(self) -> NsbComponentMetadata: ...

class NsbResult:
    @property
    def integrated_photons_cm2_ns_sr(self) -> float: ...
    @property
    def b_mag_per_arcsec2(self) -> float: ...
    @property
    def v_mag_per_arcsec2(self) -> float: ...
    @property
    def components(self) -> list[NsbComponent]: ...

class ThresholdQueryResult:
    @property
    def threshold_photons_cm2_ns_sr(self) -> float: ...
    @property
    def periods(self) -> list[tuple[datetime, datetime]]: ...

class SiteWindowContext: ...

class NsbEvaluator:
    def __init__(self, config: NsbModelConfig | None = None) -> None: ...
    @property
    def config(self) -> NsbModelConfig: ...
    def evaluate(self, query: PointQuery) -> NsbResult: ...
    def prepare_site_window_context(self, query: ThresholdQuery) -> SiteWindowContext: ...
    def periods_below_threshold(self, query: ThresholdQuery) -> ThresholdQueryResult: ...
    def periods_below_threshold_with_context(self, context: SiteWindowContext, query: ThresholdQuery) -> ThresholdQueryResult: ...
