//! Cross-validation against captured Python `darknsb` fixtures.
//!
//! Reads JSON files from `tests/golden/`, runs the same scenario through the
//! Rust crate, and:
//!   * asserts each component is within documented tolerances, and
//!   * writes a Markdown discrepancy report under `target/`.
//!
//! Tolerances are intentionally generous because the Rust pipeline currently
//! uses simplified low-precision Sun/site/coordinate models. The discrepancy
//! report is the source of truth for "how close are we to Python".

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use chrono::{DateTime, NaiveDateTime, Utc};
use nsb::{calculate, ComponentMask, ObservationRequest, Site, Source};
use serde_json::Value;
use tempoch::{Time, UTC};

const GOLDEN_DIR: &str = "tests/golden";

const REL_TOL_PER_COMPONENT: f64 = 0.05; // 5 %
const REL_TOL_TOTAL: f64 = 0.02;          // 2 %
const ABS_TOL_MAG: f64 = 0.05;            // mag/arcsec²

#[derive(Debug)]
struct Row {
    scenario: String,
    metric: &'static str,
    py: f64,
    rs: f64,
}

impl Row {
    fn diff(&self) -> f64 { self.rs - self.py }
    fn rel(&self) -> f64 { if self.py.abs() < 1e-30 { 0.0 } else { (self.rs - self.py) / self.py } }
}

fn site_from_str(s: &str) -> Site {
    Site::from_name(s).expect("unknown site")
}

fn parse_obstime(s: &str) -> Time<UTC> {
    let ndt = NaiveDateTime::parse_from_str(s, "%Y-%m-%d %H:%M:%S")
        .or_else(|_| NaiveDateTime::parse_from_str(s, "%Y-%m-%dT%H:%M:%S"))
        .expect("parse obstime");
    let dt = DateTime::<Utc>::from_naive_utc_and_offset(ndt, Utc);
    Time::<UTC>::from_chrono(dt)
}

#[test]
fn cross_validate_against_python_golden() {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(GOLDEN_DIR);
    let mut rows: Vec<Row> = Vec::new();

    let mut entries: Vec<_> = fs::read_dir(&dir)
        .expect("golden directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some("json"))
        .collect();
    entries.sort_by_key(|e| e.path());

    assert!(!entries.is_empty(), "no golden fixtures present");

    for entry in entries {
        let path = entry.path();
        let raw = fs::read_to_string(&path).expect("read fixture");
        let json: Value = serde_json::from_str(&raw).expect("valid JSON");

        let scenario = json["scenario"].as_str().unwrap().to_string();
        let inputs = &json["inputs"];

        let req = ObservationRequest {
            site: site_from_str(inputs["site"].as_str().unwrap()),
            time: parse_obstime(inputs["obstime"].as_str().unwrap()),
            source: Source::Named(inputs["source"].as_str().unwrap().to_string()),
            components: ComponentMask::ZODIACAL
                | ComponentMask::STARLIGHT
                | ComponentMask::AIRGLOW,
        };

        let result = calculate(&req).expect("nsb::calculate");

        let mut by_name: BTreeMap<&str, &nsb::NsbComponent> = BTreeMap::new();
        for c in &result.components { by_name.insert(c.name, c); }

        for component in ["zodiacal", "starlight", "airglow"] {
            let py_val = json["components"][component]["integrated"].as_f64().unwrap();
            let rs_val = by_name[component].integrated.value();
            rows.push(Row {
                scenario: scenario.clone(),
                metric: match component {
                    "zodiacal" => "ZL.integrated",
                    "starlight" => "SL.integrated",
                    _ => "AG.integrated",
                },
                py: py_val,
                rs: rs_val,
            });
        }

        let py_total = json["totals"]["integrated"].as_f64().unwrap();
        rows.push(Row { scenario: scenario.clone(), metric: "Total.integrated",
            py: py_total, rs: result.integrated.value() });

        let py_b = json["totals"]["b_mag"].as_f64().unwrap();
        let py_v = json["totals"]["v_mag"].as_f64().unwrap();
        rows.push(Row { scenario: scenario.clone(), metric: "B_mag",
            py: py_b, rs: result.b_mag.value() });
        rows.push(Row { scenario: scenario.clone(), metric: "V_mag",
            py: py_v, rs: result.v_mag.value() });
    }

    // Write the discrepancy report.
    let out_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("target");
    fs::create_dir_all(&out_dir).ok();
    let report_path = out_dir.join("nsb_discrepancy_report.md");
    let mut md = String::new();
    md.push_str("# NSB Rust ↔ Python discrepancy report\n\n");
    md.push_str("Generated by `cargo test --test cross_validation`.\n\n");
    md.push_str("| Scenario | Metric | Python | Rust | Δ (rust−py) | rel |\n");
    md.push_str("|---|---|---:|---:|---:|---:|\n");
    for r in &rows {
        md.push_str(&format!(
            "| {} | {} | {:.6e} | {:.6e} | {:+.3e} | {:+.2}% |\n",
            r.scenario, r.metric, r.py, r.rs, r.diff(), r.rel() * 100.0
        ));
    }
    fs::write(&report_path, md).expect("write report");
    eprintln!("wrote {}", report_path.display());

    // Hard tolerance assertions.
    let mut failures = Vec::new();
    for r in &rows {
        let ok = match r.metric {
            "Total.integrated" => r.rel().abs() <= REL_TOL_TOTAL,
            "B_mag" | "V_mag" => r.diff().abs() <= ABS_TOL_MAG,
            _ => r.rel().abs() <= REL_TOL_PER_COMPONENT,
        };
        if !ok {
            failures.push(format!(
                "{} / {}: py={:.4e} rs={:.4e} rel={:+.2}%",
                r.scenario, r.metric, r.py, r.rs, r.rel() * 100.0));
        }
    }
    assert!(failures.is_empty(), "out-of-tolerance metrics:\n{}", failures.join("\n"));
}
