use serde::Deserialize;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED: &str = "bundled_starlight_assets.rs";
const MAP_SCHEMA: &str = "nsb-healpix-starlight-v2";
const MANIFEST_SCHEMA: &str = "nsb-starlight-runtime-manifest-v1";

#[derive(Debug, Deserialize)]
struct Manifest {
    assets: Vec<Asset>,
}

#[derive(Debug, Deserialize)]
struct Asset {
    path: String,
    schema: String,
    sha256: String,
    calibration_status: String,
    runtime_embedded: bool,
}

fn main() {
    println!("cargo:rerun-if-changed=data/manifest.toml");
    println!("cargo:rustc-check-cfg=cfg(nsb_bundled_production_starlight)");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let data_dir = manifest_dir.join("data");
    let manifest_path = data_dir.join("manifest.toml");
    let manifest_raw = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", manifest_path.display()));
    let manifest: Manifest = toml::from_str(&manifest_raw)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", manifest_path.display()));

    let maps: Vec<&Asset> = manifest
        .assets
        .iter()
        .filter(|asset| is_production_map_asset(asset))
        .collect();
    let manifests: Vec<&Asset> = manifest
        .assets
        .iter()
        .filter(|asset| is_production_manifest_asset(asset))
        .collect();

    let generated = match (maps.as_slice(), manifests.as_slice()) {
        ([], []) => generate_unavailable(),
        ([map], [manifest]) => {
            require_registered_file(&data_dir, map);
            require_registered_file(&data_dir, manifest);
            println!("cargo:rerun-if-changed=data/{}", map.path);
            println!("cargo:rerun-if-changed=data/{}", manifest.path);
            println!("cargo:rustc-cfg=nsb_bundled_production_starlight");
            generate_available(map, manifest)
        }
        _ => panic!(
            "expected either zero or one production starlight CSV/TOML pair in data/manifest.toml; found {} maps and {} manifests",
            maps.len(),
            manifests.len()
        ),
    };

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join(GENERATED);
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
}

fn is_production_map_asset(asset: &Asset) -> bool {
    asset.schema == MAP_SCHEMA
        && asset.calibration_status.eq_ignore_ascii_case("production")
        && asset.runtime_embedded
        && asset.path.ends_with(".release.csv")
}

fn is_production_manifest_asset(asset: &Asset) -> bool {
    asset.schema == MANIFEST_SCHEMA
        && asset.calibration_status.eq_ignore_ascii_case("production")
        && asset.runtime_embedded
        && asset.path.ends_with(".manifest.toml")
}

fn require_registered_file(data_dir: &Path, asset: &Asset) {
    let path = data_dir.join(&asset.path);
    if !path.is_file() {
        panic!(
            "registered production starlight asset {} is missing from {}",
            asset.path,
            data_dir.display()
        );
    }
}

fn generate_unavailable() -> String {
    concat!(
        "// @generated by build.rs; do not edit.\n",
        "pub(crate) const BUNDLED_PRODUCTION_STARLIGHT_AVAILABLE: bool = false;\n",
    )
    .to_string()
}

fn generate_available(map: &Asset, manifest: &Asset) -> String {
    let mut out = String::from("// @generated by build.rs; do not edit.\n");
    writeln!(
        out,
        "pub(crate) const BUNDLED_PRODUCTION_STARLIGHT_AVAILABLE: bool = true;"
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const BUNDLED_PRODUCTION_STARLIGHT_MAP_PATH: &str = {:?};",
        map.path
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const BUNDLED_PRODUCTION_STARLIGHT_MAP_SHA256: &str = {:?};",
        map.sha256
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const BUNDLED_PRODUCTION_STARLIGHT_MANIFEST_PATH: &str = {:?};",
        manifest.path
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const BUNDLED_PRODUCTION_STARLIGHT_MANIFEST_SHA256: &str = {:?};",
        manifest.sha256
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const BUNDLED_PRODUCTION_STARLIGHT_MAP: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {:?}));",
        format!("/data/{}", map.path)
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const BUNDLED_PRODUCTION_STARLIGHT_MANIFEST: &str = include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {:?}));",
        format!("/data/{}", manifest.path)
    )
    .unwrap();
    writeln!(
        out,
        "siderust::assert_data_checksum!({:?}, BUNDLED_PRODUCTION_STARLIGHT_MAP.as_bytes(), {:?});",
        format!("NSB/data/{}", map.path),
        map.sha256
    )
    .unwrap();
    writeln!(
        out,
        "siderust::assert_data_checksum!({:?}, BUNDLED_PRODUCTION_STARLIGHT_MANIFEST.as_bytes(), {:?});",
        format!("NSB/data/{}", manifest.path),
        manifest.sha256
    )
    .unwrap();
    out
}
