name: Publish to crates.io

on:
  push:
    tags:
      - "v[0-9]*"

permissions:
  contents: read

jobs:
  publish:
    name: cargo publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Publish nsb
        run: bash scripts/publish-changed.sh
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
